export const enum AuthClaimDefinitions {
  OVERRIDE_USER_CLAIMS = 'OVERRIDE_USER_CLAIMS',
  MANAGE_USER_ROLES = 'MANAGE_USER_ROLES',
  MANAGE_TENANT_SPECIFIC_ROLES = 'MANAGE_TENANT_SPECIFIC_ROLES',
  MANAGE_APPLICATION_WIDE_ROLES = 'MANAGE_APPLICATION_WIDE_ROLES',
  MANAGE_CLAIMS = 'MANAGE_CLAIMS',
  CHANGE_CLAIM_PROTECTION = 'CHANGE_CLAIM_PROTECTION',
  MANAGE_TENANTS = 'MANAGE_TENANTS',
  MANAGE_USERS = 'MANAGE_USERS'
}