export const enum AuthClaimDefinitions {
  OVERRIDE_USER_CLAIMS = 'OVERRIDE_USER_CLAIMS',
  MANAGE_USER_ROLES = 'MANAGE_USER_ROLES',
  MANAGE_USER_CLAIMS = 'MANAGE_USER_CLAIMS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_CLAIMS = 'MANAGE_CLAIMS',
  CAN_OVERRIDE_CLAIM_PROTECTION = 'CAN_OVERRIDE_CLAIM_PROTECTION'
}