import { PlantsActions } from './plants/plants.actions';
import { PlantsState, PLANTS_STATE_NAME } from './plants/plants.state';

export const AUTOGENERATED_DATABASE_STATES = {
  [PLANTS_STATE_NAME]: {
    state: PlantsState,
    cacheTimeout: 999,
    loadAction: PlantsActions.LoadAll,
    clearAction: PlantsActions.Clear,
  },

};
