export const AUTHENTICATED_ROOT_PATH = '/';
export const MAIN_LAYOUT_PATH = '';
export const HOME_PATH = 'home';

export const LOGIN_PAGE_PATH = 'login';
export const ERROR_PAGE_PATH = 'error';
export const NON_AUTHENTICATED_ROOT_PATH = LOGIN_PAGE_PATH;


// FEATURE PAGES
export const ANNUAL_PLANNING_LIST_PATH = 'annual-planning-list';
export const ANNUAL_PLANNING_DETAILS_PATH = 'annual-planning-details';
export const ANNUAL_PLANNING_SCENARIO_DETAILS_PATH = 'annual-planning-scenario-details';
export const ANNUAL_PLANNING_SCENARIOS_COMPARISON_PATH = 'annual-planning-scenarios-comparison';

export const HOME_PAGE_ROUTE = [MAIN_LAYOUT_PATH, HOME_PATH];

export const ANNUAL_PLANNING_LIST_PAGE_ROUTE = [MAIN_LAYOUT_PATH, ANNUAL_PLANNING_LIST_PATH];
export const ANNUAL_PLANNING_DETAILS_PAGE_ROUTE = [MAIN_LAYOUT_PATH, ANNUAL_PLANNING_DETAILS_PATH];
export const ANNUAL_PLANNING_SCENARIO_DETAILS_PAGE_ROUTE = [MAIN_LAYOUT_PATH, ANNUAL_PLANNING_SCENARIO_DETAILS_PATH];
export const ANNUAL_PLANNING_SCENARIOS_COMPARISON_PAGE_ROUTE = [MAIN_LAYOUT_PATH, ANNUAL_PLANNING_SCENARIOS_COMPARISON_PATH];
