export enum SmzContentTheme {
    ARYA_BLUE = 'arya-blue/theme.css',
    ARYA_GREEN = 'arya-green/theme.css',
    ARYA_ORANGE = 'arya-orange/theme.css',
    ARYA_PURPLE = 'arya-purple/theme.css',
    BOOTSTRAP4_DARK_BLUE = 'bootstrap4-dark-blue/theme.css',
    BOOTSTRAP4_DARK_PURPLE = 'bootstrap4-dark-purple/theme.css',
    BOOTSTRAP4_LIGHT_BLUE = 'bootstrap4-light-blue/theme.css',
    BOOTSTRAP4_LIGHT_PURPLE = 'bootstrap4-light-purple/theme.css',
    FLUENT_LIGHT = 'fluent-light/theme.css',
    LARA_DARK_BLUE = 'lara-dark-blue/theme.css',
    LARA_DARK_INDIGO = 'lara-dark-indigo/theme.css',
    LARA_DARK_PURPLE = 'lara-dark-purple/theme.css',
    LARA_DARK_TEAL = 'lara-dark-teal/theme.css',
    LARA_LIGHT_BLUE = 'lara-light-blue/theme.css',
    LARA_LIGHT_INDIGO = 'lara-light-indigo/theme.css',
    LARA_LIGHT_PURPLE = 'lara-light-purple/theme.css',
    LARA_LIGHT_TEAL = 'lara-light-teal/theme.css',
    LUNA_AMBER = 'luna-amber/theme.css',
    LUNA_BLUE = 'luna-blue/theme.css',
    LUNA_GREEN = 'luna-green/theme.css',
    LUNA_PINK = 'luna-pink/theme.css',
    MD_DARK_DEEPPURPLE = 'md-dark-deeppurple/theme.css',
    MD_DARK_INDIGO = 'md-dark-indigo/theme.css',
    MD_LIGHT_DEEPPURPLE = 'md-light-deeppurple/theme.css',
    MD_LIGHT_INDIGO = 'md-light-indigo/theme.css',
    MDC_DARK_DEEPPURPLE = 'mdc-dark-deeppurple/theme.css',
    MDC_DARK_INDIGO = 'mdc-dark-indigo/theme.css',
    MDC_LIGHT_DEEPPURPLE = 'mdc-light-deeppurple/theme.css',
    MDC_LIGHT_INDIGO = 'mdc-light-indigo/theme.css',
    NOVA = 'nova/theme.css',
    NOVA_ACCENT = 'nova-accent/theme.css',
    NOVA_ALT = 'nova-alt/theme.css',
    RHEA = 'rhea/theme.css',
    SAGA_BLUE = 'saga-blue/theme.css',
    SAGA_GREEN = 'saga-green/theme.css',
    SAGA_ORANGE = 'saga-orange/theme.css',
    SAGA_PURPLE = 'saga-purple/theme.css',
    TAILWIND_LIGHT = 'tailwind-light/theme.css',
    VELA_BLUE = 'vela-blue/theme.css',
    VELA_GREEN = 'vela-green/theme.css',
    VELA_ORANGE = 'vela-orange/theme.css',
    VELA_PURPLE = 'vela-purple/theme.css',
    CUSTOM_DARK = 'custom-dark.css',
    CUSTOM_DARK_DIMMED = 'custom-dark-dimmed.css',
    CUSTOM_LIGHT = 'custom-light.css',
    CUSTOM_LIGHT_DIMMED = 'custom-light-dimmed.css',

}

export const SmzContentThemes: ContentTheme[] = [
    { id: SmzContentTheme.ARYA_BLUE, name: 'Arya Blue', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.ARYA_GREEN, name: 'Arya Green', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.ARYA_ORANGE, name: 'Arya Orange', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.ARYA_PURPLE, name: 'Arya Purple', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.BOOTSTRAP4_DARK_BLUE, name: 'Bootstrap 4 Dark Blue', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.BOOTSTRAP4_DARK_PURPLE, name: 'Bootstrap 4 Dark Purple', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.BOOTSTRAP4_LIGHT_BLUE, name: 'Bootstrap 4 Light Blue', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.BOOTSTRAP4_LIGHT_PURPLE, name: 'Bootstrap 4 Light Purple', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.FLUENT_LIGHT, name: 'Fluent Light', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.LARA_DARK_BLUE, name: 'Lara Dark Blue', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.LARA_DARK_INDIGO, name: 'Lara Dark Indigo', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.LARA_DARK_PURPLE, name: 'Lara Dark Purple', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.LARA_DARK_TEAL, name: 'Lara Dark Teal', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.LARA_LIGHT_BLUE, name: 'Lara Light Blue', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.LARA_LIGHT_INDIGO, name: 'Lara Light Indigo', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.LARA_LIGHT_PURPLE, name: 'Lara Light Purple', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.LARA_LIGHT_TEAL, name: 'Lara Light Teal', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.LUNA_AMBER, name: 'Luna Amber', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.LUNA_BLUE, name: 'Luna Blue', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.LUNA_GREEN, name: 'Luna Green', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.LUNA_PINK, name: 'Luna Pink', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.MDC_DARK_DEEPPURPLE, name: 'MDC Dark Deep Purple', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.MDC_DARK_INDIGO, name: 'MDC Dark Indigo', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.MDC_LIGHT_DEEPPURPLE, name: 'MDC Light Deep Purple', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.MDC_LIGHT_INDIGO, name: 'MDC Light Indigo', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.MD_DARK_DEEPPURPLE, name: 'MD Dark Deep Purple', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.MD_DARK_INDIGO, name: 'MD Dark Indigo', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.MD_LIGHT_DEEPPURPLE, name: 'MD Light Deep Purple', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.MD_LIGHT_INDIGO, name: 'MD Light Indigo', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.NOVA, name: 'Nova', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.NOVA_ACCENT, name: 'Nova Accent', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.NOVA_ALT, name: 'Nova Alt', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.RHEA, name: 'Rhea', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.SAGA_BLUE, name: 'Saga Blue', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.SAGA_GREEN, name: 'Saga Green', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.SAGA_ORANGE, name: 'Saga Orange', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.SAGA_PURPLE, name: 'Saga Purple', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.TAILWIND_LIGHT, name: 'Tailwind Light', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.VELA_BLUE, name: 'Vela Blue', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.VELA_GREEN, name: 'Vela Green', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.VELA_ORANGE, name: 'Vela Orange', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.VELA_PURPLE, name: 'Vela Purple', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.CUSTOM_DARK, name: 'Custom Dark', tone: 'dark', isDimmed: false },
    { id: SmzContentTheme.CUSTOM_DARK_DIMMED, name: 'Custom Dark Dimmed', tone: 'dark', isDimmed: true },
    { id: SmzContentTheme.CUSTOM_LIGHT, name: 'Custom Light', tone: 'light', isDimmed: false },
    { id: SmzContentTheme.CUSTOM_LIGHT_DIMMED, name: 'Custom Light Dimmed', tone: 'light', isDimmed: true },
];

export interface ContentTheme {
    id: SmzContentTheme,
    name: string,
    tone: 'dark' | 'light',
    isDimmed: boolean;
}