import { AUTOGENERATED_DATABASE_STATES } from '@state/database/state-databases.setup';
import { AuthClaimDefinitions, SmzLoader, SmzUiBuilder } from '@ngx-smz/core';
import { smzDialogsConfig } from './deprecated/smz-dialogs.config';
import { smzLayoutsConfig } from './deprecated/smz-layouts.config';
import { CustomUserTableBuilder } from './functions/custom-user-table-state';
import { showUserCreationDialog } from '@pages/proteus/functions/show-user-creation-dialog';
import { AUTHENTICATED_ROOT_PATH } from '@routes';
import { SSO_LOGIN_PATH } from '@pages/login-sso/sso.routes';
import { getInitialProteusState, PROTEUS_STATE_NAME, ProteusState } from '@pages/proteus/state/proteus.state';
import { getSsoAuthInitialState, SSO_AUTH_STATE_NAME, SsoAuthState } from '@pages/login-sso/states/sso-auth.state';
import { INSPECTIONS_STATE_NAME, InspectionsState } from '@state/database/inspections/inspections.state';
import { InspectionsActions } from '@state/database/inspections/inspections.actions';
import { ANNUAL_PLANNINGS_STATE_NAME, AnnualPlanningsState } from '@state/database/annual-plannings/annual-plannings.state';
import { AnnualPlanningsActions } from '@state/database/annual-plannings/annual-plannings.actions';
import { ANNUAL_PLANNINGS_FT_STATE_NAME, AnnualPlanningsFtState, getInitialAnnualPlanningsFtState } from '@state/features/annual-plannings/annual-plannings.state';
import { SCENARIOS_FT_STATE_NAME, ScenariosFtState, getInitialScenariosFtState } from '@state/features/scenarios/scenarios.state';
import { getInitialScenarioComparisonState, SCENARIO_COMPARISON_STATE_NAME, ScenarioComparisonState } from '@state/features/scenario-comparison/scenario-comparison.state';

declare const require;

// eslint-disable-next-line @typescript-eslint/no-var-requires
const version: string = require( '../../../../../package.json').version;
// eslint-disable-next-line @typescript-eslint/no-var-requires
const license: string = require( '../../../../../package.json').license;

export const UiBuilder: SmzUiBuilder = new SmzUiBuilder()
  .setApplicationName('Cronos Web')
  .setDialogsConfigManually(smzDialogsConfig)
  .layouts(smzLayoutsConfig)
    .setLoader(SmzLoader.SQUARE)
    .builder
  .authentication()
    .setLocalStoragePrefix('cronos')
    .mapAccessTokenData('rol', 'roles', 'array')
    .mapAccessTokenData('avatar', 'avatar', 'string')
    .mapAccessTokenData('tenant', 'tenant', 'string')
    .mapAccessTokenData('display-name', 'displayName', 'string')
    .setTenantDisplayName('Unidade de Negócio')
    .setAuthenticatedRoot(AUTHENTICATED_ROOT_PATH)
    .setNonAuthenticatedRoot(SSO_LOGIN_PATH) // SSO Customization
    .login()
      .setBackground('bg-gradient-to-r from-sky-600 from-10% via-cyan-800 via-50% to-cyan-600 to-90%')
      .useCustomLogo('assets/images/logos/horizontal-login.svg')
      .setLogoSize('large')
      .useWindowsAuthentication()
      .allowSuperuser()
      .setLoginButtonLabel('LOGIN PETROBRAS')
      .allowTenantSwitching()
      .authorization
    .builder
  .authorization()
    // .allowMultipleRolesPerUser()
    .overrideMenu('profile')
    .users()
      .customTable(CustomUserTableBuilder)
      .allowUserDeletion()
      .setAvatarPlaceholder('assets/images/avatar_dark.png')
      .addButtons()
        .item('Criar Usuário')
          .hasClaimAccess(AuthClaimDefinitions.MANAGE_USERS)
          .setCallback(() => showUserCreationDialog())
          .menu
        .back
      .authorization
    .roles().authorization
    .claims().authorization
    .tenants().authorization
    .builder
  .errorsPage()
    .clearOnError()
    .allowGoToLogin()
    .setMessage( `Ocorreu um erro com a sua solicitação. Caso persista, entre em contato com seu administrador de sistema. (${license} | ${version})`)
    .builder
  .states()
    .useCodeGenerator(AUTOGENERATED_DATABASE_STATES)

// DATABASE
  .addDatabase(ANNUAL_PLANNINGS_STATE_NAME)
    .setState(AnnualPlanningsState)
    .setLoadAction(AnnualPlanningsActions.LoadAll)
    .setClearAction(AnnualPlanningsActions.Clear)
    .state

  .addDatabase(INSPECTIONS_STATE_NAME)
    .setState(InspectionsState)
    .setLoadAction(InspectionsActions.LoadAll)
    .setClearAction(InspectionsActions.Clear)
    .state

  // FEATURE
  .addFeature(ANNUAL_PLANNINGS_FT_STATE_NAME)
    .setState(AnnualPlanningsFtState)
    .setClearFunction(getInitialAnnualPlanningsFtState)
    .state

  .addFeature(SCENARIOS_FT_STATE_NAME)
    .setState(ScenariosFtState)
    .setClearFunction(getInitialScenariosFtState)
    .state

  .addFeature(SCENARIO_COMPARISON_STATE_NAME)
    .setState(ScenarioComparisonState)
    .setClearFunction(getInitialScenarioComparisonState)
    .state

  .addFeature(PROTEUS_STATE_NAME)
    .setState(ProteusState)
    .setClearFunction(getInitialProteusState)
    .state

  // SSO Customization
  .addFeature(SSO_AUTH_STATE_NAME)
    .setState(SsoAuthState)
    .setClearFunction(getSsoAuthInitialState)
    .state

  .builder;
